In [1]:
import pandas as pd
# melb_data.to_csv('data/melb_data.csv', index=False, sep=';')
data = pd.read_csv('data/melb_data.csv', sep = ';')
display(data)

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,-37.7996 ...
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,-37.8079 ...
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,-37.8093 ...
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,126.0,1970.0,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,"-37.7969 ,..."
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,-37.8072 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,...,2.0,652.0,126.0,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,"-37.90562 , 145.16761"
13576,13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,...,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0,"-37.85927 , 144..."
13577,13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,...,4.0,436.0,126.0,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0,-37.85274 ...
13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,"-37.85908 , 1..."
13579,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,-37.81188 ...

In [ ]:
# ИЗМЕНЕНИЕ ТИПА ДАННЫХ В СТОЛБЦЕ
# воспользоваться методом astype()
# позволяет преобразовать тип данных столбца
# данные в столбцах, которые отражают количество, должны, по идее, выражаться целым числом (Car, Bedroom, Bathroom и Propertyсount), однако кодируются float64 — числом с плавающей запятой размером 64 бита
# при помощи метода astype() последовательно переопределяем столбцы на них же самих, только с изменённым типом данных: int64 — целочисленное число размером 64 бита.

In [3]:
import pandas as pd
# melb_data.to_csv('data/melb_data.csv', index=False, sep=';')
data = pd.read_csv('data/melb_data.csv', sep = ';')
#display(data)
data['Car'] = data['Car'].astype('int64')
data['Bedroom'] = data['Bedroom'].astype('int64')
data['Bathroom']= data['Bathroom'].astype('int64')
data['Propertycount'] = data['Propertycount'].astype('int64')
data['YearBuilt'] = data['YearBuilt'].astype('int64')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [ ]:
# типах данных pandas:

# object
# int64
# float64
# datetime64
# bool